# Generated by Django 2.1.7 on 2019-04-19 12:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticsodessapp', '0002_auto_20190419_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_model',
            name='movements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None),
        ),
    ]
