# Generated by Django 2.1.7 on 2019-04-19 12:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticsodessapp', '0003_auto_20190419_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_model',
            name='movements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
