# Generated by Django 2.1.7 on 2019-04-19 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticsodessapp', '0004_auto_20190419_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game_model',
            old_name='score_y',
            new_name='score_o',
        ),
    ]
