# Generated by Django 3.0.4 on 2020-03-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticsodessapp', '0005_auto_20190419_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imageUrl',
            field=models.URLField(blank=True),
        ),
    ]
