# Generated by Django 3.0.4 on 2020-03-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticsodessapp', '0006_user_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imageUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
