# Generated by Django 3.0.4 on 2020-03-14 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticsodessapp', '0007_auto_20200314_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='_user_friends_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
