# Generated by Django 3.0.4 on 2020-10-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticsodessapp', '0012_user_isusernameset'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('N', 'NOOB'), ('I', 'INTERMEDIATE'), ('P', 'PROFESSIONAL'), ('M', 'MASTER'), ('J', 'JEDI')], default='N', max_length=15),
        ),
    ]
