# Generated by Django 3.0.4 on 2020-11-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticsodessapp', '0014_user_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='full name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('userID', models.CharField(blank=True, default='', max_length=50)),
                ('socialmedia', models.CharField(max_length=10, verbose_name='social media')),
                ('accessToken', models.CharField(max_length=4096, verbose_name='access token')),
                ('refreshToken', models.CharField(max_length=4096, verbose_name='refresh token')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 's',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('Noob', 'NOOB'), ('Intermediate', 'INTERMEDIATE'), ('Professional', 'PROFESSIONAL'), ('Master', 'MASTER'), ('Jedi', 'JEDI')], default='Noob', max_length=15),
        ),
    ]
