# Generated by Django 3.0.4 on 2020-11-07 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticsodessapp', '0015_auto_20201107_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallogin',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
