# Generated by Django 3.0.4 on 2020-11-07 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticsodessapp', '0017_auto_20201107_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallogin',
            options={'verbose_name': 'Social Login'},
        ),
    ]
