# Generated by Django 3.0.4 on 2020-11-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticsodessapp', '0018_auto_20201107_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usernameUpdated',
            field=models.BooleanField(default=False),
        ),
    ]
