# Generated by Django 3.0.4 on 2020-11-09 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticsodessapp', '0019_user_usernameupdated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallogin',
            name='refreshToken',
        ),
    ]
