# Generated by Django 3.0.4 on 2020-11-09 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticsodessapp', '0020_remove_sociallogin_refreshtoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallogin',
            options={},
        ),
        migrations.RemoveField(
            model_name='sociallogin',
            name='name',
        ),
    ]
