# Generated by Django 3.0.4 on 2020-12-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticsodessapp', '0021_auto_20201109_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='images/', verbose_name='')),
            ],
        ),
    ]
