# Generated by Django 3.0.4 on 2020-12-14 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticsodessapp', '0022_imag'),
    ]

    operations = [
        migrations.AddField(
            model_name='imag',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='userimage'),
        ),
    ]
