# Generated by Django 3.0.4 on 2020-12-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticsodessapp', '0023_imag_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imag',
            name='file',
            field=models.ImageField(upload_to='images/', verbose_name='image'),
        ),
    ]
