version: "3.7"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    depends_on: 
      - db
      - redis
    env_file:
      - ./env_ticsodess
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env_db
  redis:
    restart: always
    image: redis:latest
    expose:
      - 6379
volumes:
  postgres_data:
