version: "3.7"

services:
  web:
    image: revolutions.azurecr.io/ticsodess_server_project_web_production:latest
    command: gunicorn ticsodess_server_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    environment:
      - DEBUG=0
      - SECRET_KEY=qera6u$$qb$$3j=s-@6ro4550)4&dcmn9y5_dlena8i+r@*ju&*g
      - DJANGO_ALLOWED_HOSTS=localhost ticsodessclient.azurewebsites.net 127.0.0.1 [::1]
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=postgres
      - SQL_USER=postgres
      - SQL_PASSWORD=rootroot
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
  db:
    image: postgres:12.0-alpine
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rootroot
      - POSTGRES_DB=postgres
  nginx:
    image: revolutions.azurecr.io/ticsodess_server_project_ngnix:latest
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 443:80
    depends_on:
      - web
      - daphne
  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"
  daphne:
    image: revolutions.azurecr.io/ticsodess_server_project_web_production:latest
    command: daphne -b 0.0.0.0 -p 9000 ticsodess_server_project.asgi:application
    expose: 
      - 9000
    environment:
      - DEBUG=0
      - SECRET_KEY=qera6u$$qb$$3j=s-@6ro4550)4&dcmn9y5_dlena8i+r@*ju&*g
      - DJANGO_ALLOWED_HOSTS=localhost ticsodessclient.azurewebsites.net 127.0.0.1 [::1]
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=postgres
      - SQL_USER=postgres
      - SQL_PASSWORD=rootroot
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis


volumes:
  postgres_data:
  static_volume:
